apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
  labels:
    app: hello-app
    managed-by: argocd
    chart: hello
    generated-by: "helm"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    managed-by: argocd
    generated-by: "helm"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: hello-env-config
              key: APP_NAME
        - name: DEPLOYED_BY
          valueFrom:
            configMapKeyRef:
              name: hello-env-config
              key: DEPLOYED_BY
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: env-config
          mountPath: /etc/config
      volumes:
      - name: html
        configMap:
          name: hello-html
      - name: env-config
        configMap:
          name: hello-env-config

